_wandb:
    value:
        cli_version: 0.21.3
        e:
            y6fezn349occgk2dz92424wdfak0l42u:
                cpu_count: 8
                cpu_count_logical: 16
                cudaVersion: "12.7"
                disk:
                    /:
                        total: "999261802496"
                        used: "538280448000"
                email: hhm2000@hw.ac.uk
                executable: C:\Users\hamza\anaconda3\envs\unsloth_env\python.exe
                git:
                    commit: 8e447896edd04b0458ec17b4241d199930439571
                    remote: git@github.com:hamzamooraj99/tiny-transformer-mech-interp.git
                gpu: NVIDIA GeForce RTX 3060 Laptop GPU
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 3840
                      memoryTotal: "6442450944"
                      name: NVIDIA GeForce RTX 3060 Laptop GPU
                      uuid: GPU-5599f56e-1e3c-9467-7079-b7ff85c16539
                host: C-173-G14
                memory:
                    total: "25131368448"
                os: Windows-10-10.0.22631-SP0
                program: -m src.train
                python: CPython 3.11.11
                root: C:\Users\hamza\Documents\AI\tiny-transformer-mech-interp
                startedAt: "2026-03-01T14:42:06.403671Z"
                writerId: y6fezn349occgk2dz92424wdfak0l42u
        m: []
        python_version: 3.11.11
        t:
            "1":
                - 1
                - 105
            "2":
                - 1
                - 105
            "3":
                - 2
                - 13
                - 16
            "4": 3.11.11
            "5": 0.21.3
            "8":
                - 3
            "12": 0.21.3
            "13": windows-amd64
batch_size:
    value: 64
d_model:
    value: 64
lr:
    value: 0.001
max_seq_len:
    value: 32
mlp_hidden_dim:
    value: 256
n_heads:
    value: 4
n_layers:
    value: 2
p_corrupt_train:
    value: 0
pattern_len:
    value: 8
run_name:
    value: TinyTransformerTest1
seed:
    value: 42
seq_len:
    value: 32
steps:
    value: 2000
vocab_size:
    value: 20
